### ISSUE TITLE
Incorrect binary string entropy to bytes conversion

### ISSUE THREAD

**Issue by fernandospr** [lunaticoin/semilla-moneda#1]
The following lines:
```python
random_hex = f"{int(binario, 2):x}"
random_bin = bytes.fromhex(random_hex)
```
would fail to convert some binary string entropies to bytes.

E.g. If `binario = '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'` then `random_hex` would be `'0'` and `bytes.fromhex(random_hex)` would fail.

The expected result for the example entropy above should be:
* Last word: `about`
* Mnemonic sentence: `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about`

**Comment by sr-gi** [comment]
Closed via #2
